"""DataHub writer — mutations for tags, descriptions, lineage, ownership."""

from datahub.sdk.main_client import DataHubClient


class DataHubWriter:
    def __init__(self, client: DataHubClient):
        self.client = client

    def add_tag(self, dataset_urn: str, tag_urn: str) -> bool:
        try:
            entity = self.client.entities.get(str(dataset_urn))
            entity.add_tag(tag_urn)
            self.client.entities.update(entity)
            return True
        except Exception as e:
            print(f"Error adding tag: {e}")
            return False

    def set_description(self, dataset_urn: str, description: str) -> bool:
        try:
            entity = self.client.entities.get(str(dataset_urn))
            entity.set_description(description)
            self.client.entities.update(entity)
            return True
        except Exception as e:
            print(f"Error updating description: {e}")
            return False

    def add_lineage(self, upstream_urn: str, downstream_urn: str, text: str = "") -> bool:
        try:
            self.client.lineage.add_lineage(
                upstream=upstream_urn, downstream=downstream_urn,
                column_lineage=False, transformation_text=text,
            )
            return True
        except Exception as e:
            print(f"Error adding lineage: {e}")
            return False

    def write_back(self, dataset_urn: str, upstream_urns: list[str], model_name: str) -> dict:
        results = {"tagged": False, "description": False, "lineage": False}
        results["tagged"] = self.add_tag(dataset_urn, "urn:li:tag:AutoPipeline")
        try:
            entity = self.client.entities.get(str(dataset_urn))
            desc = entity.description or ""
            new_desc = f"{desc}\n\n---\n*Generated by AutoPipeline*"
            results["description"] = self.set_description(dataset_urn, new_desc)
        except Exception:
            pass
        ok = True
        for src in upstream_urns:
            if not self.add_lineage(src, dataset_urn, f"AutoPipeline: {model_name}"):
                ok = False
        results["lineage"] = ok
        return results
