"""Writer — writes generated metadata back to the DataHub graph.

Uses the DataHub SDK entity API for mutations:
- add_tags, remove_tags
- update_description
- add_owners, add_glossary_terms
- add_lineage
"""

from typing import Optional

from datahub.sdk.main_client import DataHubClient

from autopipeline.context import DatasetContext


class DataHubWriter:
    """Writes pipeline metadata back to the DataHub graph."""

    def __init__(self, client: DataHubClient):
        self.client = client

    def add_tag_to_dataset(self, dataset_urn: str, tag_urn: str) -> bool:
        """Add a tag to a dataset."""
        try:
            entity = self.client.entities.get(str(dataset_urn))
            entity.add_tag(tag_urn)
            self.client.entities.update(entity)
            return True
        except Exception as e:
            print(f"Error adding tag {tag_urn} to {dataset_urn}: {e}")
            return False

    def set_description(self, dataset_urn: str, description: str) -> bool:
        """Update the description of a dataset."""
        try:
            entity = self.client.entities.get(str(dataset_urn))
            entity.set_description(description)
            self.client.entities.update(entity)
            return True
        except Exception as e:
            print(f"Error updating description for {dataset_urn}: {e}")
            return False

    def add_owner(
        self, dataset_urn: str, owner_urn: str, owner_type: str = "TECHNICAL_OWNER"
    ) -> bool:
        """Add an owner to a dataset."""
        try:
            entity = self.client.entities.get(str(dataset_urn))
            entity.add_owner(owner_urn, owner_type)
            self.client.entities.update(entity)
            return True
        except Exception as e:
            print(f"Error adding owner {owner_urn} to {dataset_urn}: {e}")
            return False

    def add_lineage(
        self,
        upstream_urn: str,
        downstream_urn: str,
        transformation_text: Optional[str] = None,
    ) -> bool:
        """Add lineage between two datasets."""
        try:
            self.client.lineage.add_lineage(
                upstream=upstream_urn,
                downstream=downstream_urn,
                column_lineage=False,
                transformation_text=transformation_text,
            )
            return True
        except Exception as e:
            print(f"Error adding lineage {upstream_urn} -> {downstream_urn}: {e}")
            return False

    def add_generated_model_lineage(
        self,
        target_urn: str,
        upstream_urns: list[str],
        model_name: str,
    ) -> bool:
        """Add lineage from the generated model back to its sources.

        This is the key write-back operation: it records in DataHub
        that the generated model transforms upstream data into the target.
        """
        ok = True
        for src_urn in upstream_urns:
            if not self.add_lineage(
                upstream_urn=src_urn,
                downstream_urn=target_urn,
                transformation_text=f"AutoPipeline generated transformation: {model_name}",
            ):
                ok = False
        return ok

    def tag_as_auto_generated(
        self,
        dataset_urn: str,
        tag_urn: str = "urn:li:tag:AutoPipeline",
    ) -> bool:
        """Tag a dataset as generated by AutoPipeline."""
        # First create the tag if it doesn't exist (DataHub auto-creates on use)
        return self.add_tag_to_dataset(dataset_urn, tag_urn)

    def write_back_pipeline_metadata(
        self,
        dataset_urn: str,
        generated_sql: str,
        upstream_urns: list[str],
        model_name: str,
    ) -> dict:
        """Full write-back: tag, describe, add lineage.

        Returns a dict of what was done and whether each step succeeded.
        """
        results = {
            "tagged": False,
            "description_updated": False,
            "lineage_added": False,
        }

        # Tag as AutoPipeline-generated
        results["tagged"] = self.tag_as_auto_generated(dataset_urn)

        # Update description with generation info
        try:
            entity = self.client.entities.get(str(dataset_urn))
            existing_desc = entity.description or ""
            new_desc = (
                f"{existing_desc}\n\n"
                f"---\n"
                f"*Generated by AutoPipeline on {__import__('datetime').datetime.utcnow().isoformat()}Z*\n"
                f"*Model: {model_name}*"
            )
            results["description_updated"] = self.set_description(
                dataset_urn, new_desc
            )
        except Exception as e:
            print(f"Error updating description: {e}")

        # Add lineage from sources -> target
        results["lineage_added"] = self.add_generated_model_lineage(
            target_urn=dataset_urn,
            upstream_urns=upstream_urns,
            model_name=model_name,
        )

        return results
