{{ config(
    materialized='table',
    description='### order\_details

The `order_details` table is a central hub for order information, consolidating data from various upstream sources to provide a comprehensive view of customer orders, products, and fulfillment. This table is a critical component of the order entry data ecosystem, enabling data-driven decision making and reporting across the organization.

The table is constructed by joining data from several source tables, including [@table_name](urn:li:dataset:(urn:li:dataPlatform:dbt,order_entry_db.order_entry.orders,PROD)), [@table_name](urn:li:dataset:(urn:li:dataPlatform:dbt,order_entry_db.order_entry.customers,PROD)), [@table_name](urn:li:dataset:(urn:li:dataPlatform:dbt,order_entry_db.order_entry.addresses,PROD)), [@table_name](urn:li:dataset:(urn:li:dataPlatform:dbt,order_entry_db.order_entry.countries,PROD)), [@table_name](urn:li:dataset:(urn:li:dataPlatform:dbt,order_entry_db.order_entry.regions,PROD)), [@table_name](urn:li:dataset:(urn:li:dataPlatform:dbt,order_entry_db.order_entry.warehouses,PROD)), [@table_name](urn:li:dataset:(urn:li:dataPlatform:dbt,order_entry_db.order_entry.order_items,PROD)), [@table_name](urn:li:dataset:(urn:li:dataPlatform:dbt,order_entry_db.order_entry.products,PROD)), [@table_name](urn:li:dataset:(urn:li:dataPlatform:dbt,order_entry_db.order_entry.product_categories,PROD)), and [@table_name](urn:li:dataset:(urn:li:dataPlatform:dbt,order_entry_db.order_entry.promotions,PROD)).

The `order_details` table is consumed by several downstream systems, including a Snowflake view, Tableau dashboards, Power BI reports, and a Looker view. These downstream consumers leverage the comprehensive order data to support a variety of use cases, such as sales analytics, customer segmentation, inventory management, and marketing campaign evaluation.

The table is a materialized view, meaning the data is pre-computed and stored in a physical table for efficient querying. It has a grain of one row per order line item, providing detailed information about each product ordered, including pricing, discounts, inventory status, and delivery details.

The `order_details` table does contain some personally identifiable information (PII) data, such as customer names, email addresses, and phone numbers. As such, access to this table should be carefully managed and monitored in accordance with your organization's data privacy policies.

&nbsp;

---
*Generated by AutoPipeline on 2026-07-16T14:44:16.934446Z*
*Model: daily_revenue_report*

---
*Generated by AutoPipeline on 2026-07-16T14:45:00.263486Z*
*Model: daily_revenue_report*

---
*Generated by AutoPipeline on 2026-07-16T14:45:18.679618Z*
*Model: daily_revenue_report*',
    tags=[' None})', ' None})', ' None})']
) }}

/*
  AutoPipeline Generated: order_details_revenue
  Generated at: 2026-07-16T14:46:49.089793+00:00
  Target: urn:li:dataset:(urn:li:dataPlatform:dbt,b2fd91.ORDER_ENTRY_DB.analytics.order_details,PROD)
  Sources: order_entry_db.order_entry.promotions, order_entry_db.order_entry.addresses, order_entry_db.order_entry.countries, order_entry_db.order_entry.customers, order_entry_db.order_entry.inventories, order_entry_db.order_entry.order_items, order_entry_db.order_entry.orders, order_entry_db.order_entry.products, order_entry_db.order_entry.regions, order_entry_db.order_entry.warehouses, order_entry_db.order_entry.product_categories
*/

WITH

promotions AS (
    SELECT
        promotion_id::NUMBER AS promotion_id,        promotion_name::TEXT AS promotion_name,        promotion_start_date::TEXT AS promotion_start_date,        promotion_end_date::TEXT AS promotion_end_date,        promotion_description::TEXT AS promotion_description,        promotion_cost::FLOAT AS promotion_cost    FROM {{ source('order_entry_db', 'promotions') }}
),

addresses AS (
    SELECT
        address_id::NUMBER AS address_id,        customer_id::NUMBER AS customer_id,        date_created::TEXT AS date_created,        address_line1::TEXT AS address_line1,        address_line2::TEXT AS address_line2,        town_city::TEXT AS town_city,        country_id::NUMBER AS country_id,        zipcode::NUMBER AS zipcode,        region_id::NUMBER AS region_id    FROM {{ source('order_entry_db', 'addresses') }}
),

countries AS (
    SELECT
        country_id::NUMBER AS country_id,        country_name::TEXT AS country_name,        country_code::TEXT AS country_code,        nls_territory::TEXT AS nls_territory    FROM {{ source('order_entry_db', 'countries') }}
),

customers AS (
    SELECT
        customer_id::NUMBER AS customer_id,        cust_first_name::TEXT AS cust_first_name,        cust_last_name::TEXT AS cust_last_name,        nls_language::TEXT AS nls_language,        nls_territory::TEXT AS nls_territory,        credit_limit::FLOAT AS credit_limit,        cust_email::TEXT AS cust_email,        account_mgr_id::NUMBER AS account_mgr_id,        customer_since::TEXT AS customer_since,        customer_class::TEXT AS customer_class,        suggestions::TEXT AS suggestions,        dob::TEXT AS dob,        mailshot::NUMBER AS mailshot,        partner_mailshot::NUMBER AS partner_mailshot,        phone_number::TEXT AS phone_number,        address_line1::TEXT AS address_line1,        address_line2::TEXT AS address_line2,        address_line3::TEXT AS address_line3,        town_city::TEXT AS town_city,        country_id::NUMBER AS country_id,        zipcode::NUMBER AS zipcode,        region_id::NUMBER AS region_id    FROM {{ source('order_entry_db', 'customers') }}
),

inventories AS (
    SELECT
        product_id::NUMBER AS product_id,        warehouse_id::NUMBER AS warehouse_id,        quantity_on_hand::NUMBER AS quantity_on_hand,        restock_level::NUMBER AS restock_level,        max_stock_level::NUMBER AS max_stock_level,        reorder_quantity::NUMBER AS reorder_quantity    FROM {{ source('order_entry_db', 'inventories') }}
),

order_items AS (
    SELECT
        order_id::NUMBER AS order_id,        line_item_id::NUMBER AS line_item_id,        product_id::NUMBER AS product_id,        unit_price::FLOAT AS unit_price,        quantity::NUMBER AS quantity,        dispatch_date::TEXT AS dispatch_date,        return_date::TEXT AS return_date,        gift_wrap::TEXT AS gift_wrap,        condition::TEXT AS condition,        supplier_id::NUMBER AS supplier_id,        estimated_delivery::TEXT AS estimated_delivery    FROM {{ source('order_entry_db', 'order_items') }}
),

orders AS (
    SELECT
        order_id::NUMBER AS order_id,        order_date::TEXT AS order_date,        order_mode::TEXT AS order_mode,        customer_id::NUMBER AS customer_id,        order_status::NUMBER AS order_status,        order_total::FLOAT AS order_total,        sales_rep_id::NUMBER AS sales_rep_id,        promotion_id::FLOAT AS promotion_id,        warehouse_id::NUMBER AS warehouse_id,        delivery_type::TEXT AS delivery_type,        cost_of_delivery::FLOAT AS cost_of_delivery,        wait_till_complete_yn::TEXT AS wait_till_complete_yn,        billing_address_id::NUMBER AS billing_address_id,        delivery_address_id::NUMBER AS delivery_address_id,        payment_method_code::TEXT AS payment_method_code    FROM {{ source('order_entry_db', 'orders') }}
),

products AS (
    SELECT
        product_id::NUMBER AS product_id,        product_name::TEXT AS product_name,        product_description::TEXT AS product_description,        category_id::NUMBER AS category_id,        weight_class::NUMBER AS weight_class,        warranty_period::TEXT AS warranty_period,        supplier_id::NUMBER AS supplier_id,        product_status::TEXT AS product_status,        list_price::FLOAT AS list_price,        min_price::FLOAT AS min_price,        catalog_url::TEXT AS catalog_url,        date_added::TEXT AS date_added    FROM {{ source('order_entry_db', 'products') }}
),

regions AS (
    SELECT
        region_id::NUMBER AS region_id,        region_name::TEXT AS region_name,        country_id::NUMBER AS country_id,        nls_language::TEXT AS nls_language    FROM {{ source('order_entry_db', 'regions') }}
),

warehouses AS (
    SELECT
        warehouse_id::NUMBER AS warehouse_id,        warehouse_name::TEXT AS warehouse_name,        location_id::NUMBER AS location_id,        wh_geo_location::TEXT AS wh_geo_location    FROM {{ source('order_entry_db', 'warehouses') }}
),

product_categories AS (
    SELECT
        category_id::NUMBER AS category_id,        category_name::TEXT AS category_name,        category_description::TEXT AS category_description,        parent_category_id::FLOAT AS parent_category_id    FROM {{ source('order_entry_db', 'product_categories') }}
),

joined AS (
    SELECT
        order_id,        order_date,        order_mode,        order_status,        order_total,        cost_of_delivery,        delivery_type,        wait_till_complete_yn,        payment_method_code,        customer_id,        cust_first_name,        cust_last_name,        cust_email,        phone_number,        customer_class,        billing_address_line1,        billing_address_line2,        billing_town_city,        billing_country,        billing_zipcode,        billing_region,        shipping_address_line1,        shipping_address_line2,        shipping_town_city,        shipping_country,        shipping_zipcode,        shipping_region,        warehouse_id,        warehouse_name,        promotion_id,        promotion_name,        promotion_description,        line_item_id,        product_id,        product_name,        product_description,        category_id,        category_name,        unit_price,        quantity,        line_total,        dispatch_date,        return_date,        gift_wrap,        condition,        estimated_delivery,        list_price,        product_status,        quantity_on_hand,        stock_status,        discount_amount,        discount_percent,        delivery_status,        return_status,        updated_at    FROM promotions
    LEFT JOIN order_entry_db.order_entry.addresses
        ON order_entry_db.order_entry.promotions.id = order_entry_db.order_entry.addresses.id
    LEFT JOIN order_entry_db.order_entry.countries
        ON order_entry_db.order_entry.promotions.id = order_entry_db.order_entry.countries.id
    LEFT JOIN order_entry_db.order_entry.customers
        ON order_entry_db.order_entry.promotions.id = order_entry_db.order_entry.customers.id
    LEFT JOIN order_entry_db.order_entry.inventories
        ON order_entry_db.order_entry.promotions.id = order_entry_db.order_entry.inventories.id
    LEFT JOIN order_entry_db.order_entry.order_items
        ON order_entry_db.order_entry.promotions.id = order_entry_db.order_entry.order_items.id
    LEFT JOIN order_entry_db.order_entry.orders
        ON order_entry_db.order_entry.promotions.id = order_entry_db.order_entry.orders.id
    LEFT JOIN order_entry_db.order_entry.products
        ON order_entry_db.order_entry.promotions.id = order_entry_db.order_entry.products.id
    LEFT JOIN order_entry_db.order_entry.regions
        ON order_entry_db.order_entry.promotions.id = order_entry_db.order_entry.regions.id
    LEFT JOIN order_entry_db.order_entry.warehouses
        ON order_entry_db.order_entry.promotions.id = order_entry_db.order_entry.warehouses.id
    LEFT JOIN order_entry_db.order_entry.product_categories
        ON order_entry_db.order_entry.promotions.id = order_entry_db.order_entry.product_categories.id
)

final AS (
    SELECT
        order_id,        order_date,        order_mode,        order_status,        order_total,        cost_of_delivery,        delivery_type,        wait_till_complete_yn,        payment_method_code,        customer_id,        cust_first_name,        cust_last_name,        cust_email,        phone_number,        customer_class,        billing_address_line1,        billing_address_line2,        billing_town_city,        billing_country,        billing_zipcode,        billing_region,        shipping_address_line1,        shipping_address_line2,        shipping_town_city,        shipping_country,        shipping_zipcode,        shipping_region,        warehouse_id,        warehouse_name,        promotion_id,        promotion_name,        promotion_description,        line_item_id,        product_id,        product_name,        product_description,        category_id,        category_name,        unit_price,        quantity,        line_total,        dispatch_date,        return_date,        gift_wrap,        condition,        estimated_delivery,        list_price,        product_status,        quantity_on_hand,        stock_status,        discount_amount,        discount_percent,        delivery_status,        return_status,        updated_at    FROM joined)

SELECT * FROM final